version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: last_seen_approx
    env_file:
      ./.env
    ports:
      - "5434:5432"
    restart:
        unless-stopped
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 8041:80
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      ./.env
    expose:
      - 8000
    ports:
      - 9000:8000
    depends_on: 
      - database
    volumes:
      - ./logs:/code/src/logs